#!/bin/bash

echo '<<<crontab_access_check>>>'

USR=oracle

CRON="crontab -u $USR -l"

if $CRON > /dev/null 2>&1; then
    echo "Successfully Command Executed"
    exit 0
else
    echo "Failed Command"
    exit 1
fi
