#!/bin/bash

echo '<<<crontab_access_check>>>'

USR=oracle

CRON="crontab -u $USR -l"

if $CRON > /dev/null 2>&1; then
    echo "Command Executed Successfully"
    exit 0
else
    echo "Command Failed"
    exit 1
fi
