#!/bin/bash

echo '<<<crontab_access_check>>>'

USR=oracle

CRON="crontab -u $USR -l"

echo "Checked user $USR"

if getent passwd $USR > /dev/null 2>&1; then
    if $CRON > /dev/null 2>&1; then
        echo "0 ${USR}_crontab_access_check - \"Successful Command Execution\""
    else
        echo "2 ${USR}_crontab_access_check - \"Failed-CRON Command\""
    fi
else
    echo "0 ${USR}_crontab_access_check - \"No user ${USR} found\""
fi


